# Generated by Django 4.0.6 on 2022-09-14 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tarefa_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contato'),
        ),
    ]
